### ISSUE TITLE
"Dead angles" while placing and breaking blocks.

### ISSUE THREAD

**Issue by MajsterTynek** [cabaletta/baritone#1121]
## Some information
Operating system: Windows10 version1903 build18362.449
Java version: 1.8.0_51 64bit
Minecraft version: 1.12.2-forge1.12.2-14.23.5.2847
Baritone version: 1.2.10
Forge mods (if used): Zyin's HUD

## Exception, error or logs
No logs related to this issue.

## How to reproduce
A. Using 'click' and/or 'sel ca' try to clear cuboid (prefelably 16x16x8h)
until Baritone encounters dead angle and 
gets stuck in endless loop of breaking.

B. Using 'sel set' or 'sel replace air' try to fill floor, 
issuing command from higher ground, until [...] placing.

## Description
Applies to servers with anticheat, for eg. 2b2t.
Seems like Baritone chooses block faces and/or 
aims off choosen faces while placing/breaking.
Such action might not be accepted and aborted by AC.

Distance from block is not important in this case.
(I have used temporary fix with decreased reach.) 

Visually it looks like player's character is aiming 
towards block's: edge, corner or face at angle close 0.

Screenshots: // Those will be included tommorow
// I have to crop coords from them before posting

## Final checklist
- [✓] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [✓] I have included logs, exceptions and / or steps to reproduce the issue.
- [✓] I have not used any OwO's or UwU's in this issue. (Will it hurt if I did so?)

**Comment by leijurv** [comment]
im 99% sure this was fixed by allowing you to configure https://github.com/cabaletta/baritone/commit/2ae16d8bb1cd6bed87fe2a4858ac2e5458911079 to exactly match the server. i heard for 2b2t it needs to be changed from 4.5 to 4.3 according to thebes

**Comment by MajsterTynek** [comment]
@leijurv I have used fix you gave me on Discord, 
but somehow my chars still get stuck in these cases…

EDIT: Or I am that dumb I forgot to set it to 4.3...
I must retry everything again. Issue might be inavalid. :F
I will tell if I still encounter the problem.

**Comment by ThebesAndSound** [comment]
yep 4.3 has been working for me

**Comment by MajsterTynek** [comment]
Sadly, #blockreachreachdistance is not implemented in 1.2.10.
Using 4.3 reach, problems with breaking are gone, but with placing still exist.
Now it tries to place blocks trough other blocks. lol

I think I need to edit issue and get some cases to report.

**Comment by ThebesAndSound** [comment]
I haven't noticed it having problems with reach distance placing or it trying to place through blocks, and I have been building quite a bit on 2b. Easy way to really check if configuring reach distance really doesn't apply to placing is to set it very low and see what happens. My suspicion is that you are just having block lag and ghost blocks on 2b.

**Comment by MajsterTynek** [comment]
I have NoGlitchBlocks module enabled in my client, 
so blocks don't appear until server accepts that they are placed.
I cannot go on 2b2t and test it, because of time outs. :/

**Comment by lostallmymoney** [comment]
here is the file with 4.3 as value so you can switch it in the impact jar or baritone jar :

[IPlayerController.zip](https://github.com/cabaletta/baritone/files/3846468/IPlayerController.zip)

**Comment by lostallmymoney** [comment]
@MajsterTynek @ThebesAndSound

**Comment by RileyGuy** [comment]
I tried popping that file into my impact jar under the relevant path but the setting doesn't become available. @lostallmymoney

**Comment by lostallmymoney** [comment]
> I tried popping that file into my impact jar under the relevant path but the setting doesn't become available. @lostallmymoney

It's simply the value changed from 4.5 to 4.3 if you need the setting check the new compiled fork i made. I can also make the file 4.1 or 4 if you need

**Comment by reisern** [comment]
> It's simply the value changed from 4.5 to 4.3 if you need the setting check the new compiled fork i made. I can also make the file 4.1 or 4 if you need

I'm getting this glitch on another server, how do I fix this?

**Comment by MajsterTynek** [comment]
> I'm getting this glitch on another server, how do I fix this?
`#blockreachdistance <distance>`
for eg. `#blockreachdistance 4.0`
Install lates version of Baritone 1.2.12 (if you use 1.12.2)

**Comment by S-B99** [comment]
Closed as resolved.
